=== Kasumi-chan18/assignment-1--principles-of-databases--cs-365--fall-2026/xml/student.dtd
<!-- The root element 'students' contains one or more 'student' elements -->
<!ELEMENT students (student+)>

<!-- The 'student' element contains personal and academic information.
     The '+' means there must be at least one student element in the XML. -->
<!ELEMENT student (first, middle, last, preferred, email, phone, year, gpa, major, minor, status, advisor, admit, grad)>
<!-- The 'student' element must have a unique 'id' attribute -->
<!ATTLIST student id CDATA #REQUIRED>

<!-- Individual elements for student names -->
<!ELEMENT first (#PCDATA)>        <!-- First name of the student -->
<!ELEMENT middle (#PCDATA)>       <!-- Middle name (optional)-->
<!ELEMENT last (#PCDATA)>         <!-- Last name of the student -->
<!ELEMENT preferred (#PCDATA)>    <!-- Preferred name or nickname (optional) -->

<!-- Contact information elements -->
<!ELEMENT email (#PCDATA)>        <!-- Email address -->
<!ELEMENT phone (#PCDATA)>        <!-- Phone number (optional) -->

<!-- Academic information elements -->
<!ELEMENT year (#PCDATA)>         <!-- Academic year (e.g., freshman, sophomore) -->
<!ELEMENT gpa (#PCDATA)>          <!-- Grade Point Average (gpa)-->
<!ELEMENT major (#PCDATA)>        <!-- Major field of study -->
<!ELEMENT minor (#PCDATA)>        <!-- Minor field of study (optional) -->
<!ELEMENT status (#PCDATA)>       <!-- Enrollment status (e.g., full-time, part-time) -->
<!ELEMENT advisor (#PCDATA)>      <!-- Academic advisor assigned to the student -->
<!ELEMENT admit (#PCDATA)>        <!-- Admission date -->
<!ELEMENT grad (#PCDATA)>         <!-- Graduation date -->

=== Kasumi-chan18/assignment-1--principles-of-databases--cs-365--fall-2026/xml/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE students SYSTEM "student.dtd">
<students>
  <student id="1234567">
    <first>Gordon</first>
    <middle>Matthew</middle>
    <last>Sumner</last>
    <preferred>"Sting"</preferred>
    <email>&lt;sting@thepolice.com&gt;</email>
    <phone>212.123.4567</phone>
    <year>Freshman</year>
    <gpa>4.0</gpa>
    <major>Music</major>
    <minor>English</minor>
    <status>Full-time</status>
    <advisor>Andy Summers</advisor>
    <admit>08-25-1969</admit>
    <grad>05-01-1973</grad>
  </student>

  <student id="4567890">
    <first>Kim</first>
    <middle></middle>
    <last>Thayil</last>
    <preferred></preferred>
    <email>&lt;kim@soundgarden.com&gt;</email>
    <phone>206.123.4567</phone>
    <year>Sophomore</year>
    <gpa>3.0</gpa>
    <major>Philosophy</major>
    <minor>Music</minor>
    <status>Full-time</status>
    <advisor>Chris Cornell</advisor>
    <admit>08-25-1978</admit>
    <grad>05-01-1982</grad>
  </student>

  <student id="8302438">
    <first>Saul</first>
    <middle></middle>
    <last>Hudson</last>
    <preferred>"Slash"</preferred>
    <email>&lt;slash@gnr.com&gt;</email>
    <phone>213.456.8392</phone>
    <year>Senior</year>
    <gpa>2.0</gpa>
    <major>Music</major>
    <minor>Criminal Justice</minor>
    <status>Part-time</status>
    <advisor>Axl Rose</advisor>
    <admit>08-25-1983</admit>
    <grad>05-01-1987</grad>
  </student>

  <student id="2983928">
    <first>Emily</first>
    <middle></middle>
    <last>Kokal</last>
    <preferred></preferred>
    <email>&lt;emily@warpaint.com&gt;</email>
    <phone>213.123.7654</phone>
    <year>Junior</year>
    <gpa>3.8</gpa>
    <major>Political Science</major>
    <minor>Law</minor>
    <status>Full-time</status>
    <advisor>Jenny Lee Lindberg</advisor>
    <admit>08-25-1998</admit>
    <grad>05-01-2002</grad>
  </student>

  <student id="7645726">
    <first>Mike</first>
    <middle></middle>
    <last>Inez</last>
    <preferred></preferred>
    <email>&lt;mike@aic.com&gt;</email>
    <phone>213.444.3323</phone>
    <year>Sophomore</year>
    <gpa>4.0</gpa>
    <major>Business Management</major>
    <minor>Math</minor>
    <status>Full-time</status>
    <advisor>Jerry Cantrell</advisor>
    <admit>08-25-1984</admit>
    <grad>05-01-1988</grad>
  </student>
</students>
